### ISSUE TITLE
Decouple Styles 

### ISSUE THREAD

**Issue by nexon** [buskerone/basic-RN-example-project#8]
Should remove **const** style inside the components and create a separate file/class/whatever that contains the differences styles for each components (or even create a separated style file for each component that may require it.).

Sadly, JavaScript doesn't have any kind of contract (like interface or protocols). Doing it in this way you could decouple a lot of other parts of the app and maintain abstracted some things (i.e styles). This is basically the last principles of SOLID. (Dependency Inversion). But... is only an idea.

**Comment by buskerone** [comment]
Agree! I was planning to do that 😀
Yeah, I miss Swift protocols 😔. I'll tackle this. Thanks @nexon

**Comment by buskerone** [comment]
Done.
